CREATE TABLE [TABELA DE VENDEDORES]
([MATRICULA] VARCHAR(5)NOT NULL, 
[NOME]VARCHAR(100)NULL, 
[PERCENTUAL COMISSAO] FLOAT NOT NULL)

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_TABELA_DE_VENDEDORES
PRIMARY KEY CLUSTERED(MATRICULA)

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSAO])
VALUES
('00239','Alberto de Sá Verneck', 0.08)

SELECT * FROM [TABELA DE VENDEDORES]