INSERT INTO [TABELA DE PRODUTOS]
VALUES
('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '788975';

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET','Maça', '1,5 Litros', 18.01);

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '788975';

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, [PREÇO DE LISTA], SABOR)
VALUES
('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 18.01, 'Maça')

INSERT INTO [TABELA DE PRODUTOS]
VALUES
('788976', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '', 'Maça',18.01)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '788976';