INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml','Cereja/Maça', 8.41)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002767'

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml',NULL, 8.41)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002767'

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', ' ', '',NULL, 8.41)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
(NULL, 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml','Cereja/Maça', 8.41)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] IS NULL

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(20) NOT NULL;

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
(NULL, 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml','Cereja/Maça', 8.41)

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml','Cereja/Maça', 8.41)

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002767'

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] )
VALUES
('1002767', 'Videira do Campo - 700 ml - Cereja/Maça', 'Garrafa', '700 ml','Cereja/Maça', 8.41)