-------------- FUNÇÕES STRING -------------

-- LTRIM RETIRA ESPAÇOS A ESQUERDA
SELECT LTRIM('          OLA')

--RTRIM RETIRA ESPAÇOS A DIREITA
SELECT RTRIM('TUDO BEM?         ')

-- CONCAT CONCATENA STRINGS
SELECT CONCAT('OLÁ ' , 'MUNDO!')

-- CONCAT USANDO SINAL DE +
SELECT 'OLÁ ' + 'TUDO BEM?'

-- LEFT RETORNA APENAS OS PRIMEIROS CARACTERES A ESQUERDA
SELECT LEFT('RUA AUGUSTA',3)         -- RUA

--RIGHT RETORNA APENAS OS ULTIMOS CARACTERES A DIREITA
SELECT RIGHT('RUA AUGUSTA', 7)       -- AUGUSTA

-- UPPER TRANSFORMA EM MAIUSCULAS
SELECT UPPER('rua augusta')     -- RUA AUGUSTA

--LOWER TRANSFORMA EM MINÚSCULAS
SELECT LOWER('RUA AUGUSTA'    -- rua augusta

-- REPLACE SUBSTITUI STRINGS
SELECT REPLACE('R. AUGUSTA', 'R.', 'RUA') --RUA AUGUSTA

-- SUBSTRING PEGA UMA FATIA DA STRING
SELECT SUBSTRING('RUA AUGUSTA', 5, 3) -- AUG A PARTIR DA 5 POSICAO OS 3 CARACTERES SEGUINTES

--LEN RETORNA O TAMANHO DA CADEIA DE CARACTERES
SELECT LEN('RUA AUGUSTA') --11

---------- EXERCICIOS ------
SELECT * FROM [TABELA DE CLIENTES]

SELECT CONCAT(NOME, ' ( ', CPF, ') ') FROM [TABELA DE CLIENTES]

--Faça uma consulta que lista o nome do cliente e o endereço completo (com rua, bairro, cidade e estado).

SELECT CONCAT('NOME: ',NOME, '. ENDEREÇO: ', [ENDERECO 1], ' ' , BAIRRO, ' ', CIDADE, ' ', ESTADO) 
FROM [TABELA DE CLIENTES]

SELECT NOME, CONCAT([ENDERECO 1], ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS ENDERECO_COMPLETO
FROM [TABELA DE CLIENTES]