SELECT CEILING(12.356565)        -- RETORNA O MAIOR INTEIRO PROXIMO AO NÚMERO

SELECT FLOOR(12.356565)          -- RETORNA O MENOR INTEIRO PROXIMO AO NÚMERO 

SELECT RAND()                    -- RETORNA UM FLOAT ALEATÓRIO ENTRE 0 E 1

SELECT ROUND(12.2225665659, 2)   -- RETORNA UM VALOR ARREDONDADO


-- EXEMPLO: RETORNAR QUANTIDADE X PREÇO, ARREDONDANDO 2 CASAS DECIMAIS(CENTAVOS)
SELECT QUANTIDADE, PREÇO, ROUND((QUANTIDADE * PREÇO), 2)
FROM [ITENS NOTAS FISCAIS]

-- EXERCÍCIO Na tabela de notas fiscais, temos o valor do imposto. Já na tabela de itens, temos a quantidade 
--e o faturamento. Calcule o valor do imposto pago no ano de 2016, arredondando para o menor inteiro.
 
 
SELECT YEAR(DATA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PREÇO))) 
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA)



