select * from [TABELA DE CLIENTES]

select ESTADO, [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT [NOME DO PRODUTO], EMBALAGEM FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM 

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE [ESTADO] = 'SP' GROUP BY BAIRRO, ESTADO

-- EXERCICIO: Aproveitando o exercício anterior, quantos itens de venda existem 
-- com a maior quantidade de venda para o produto '1101035'?

SELECT [CODIGO DO PRODUTO], MAX(QUANTIDADE) AS QUANT FROM [ITENS NOTAS FISCAIS]  
	WHERE [CODIGO DO PRODUTO] = '1101035' GROUP BY [CODIGO DO PRODUTO]

-- SOLUCAO DO PROFESSOR

SELECT COUNT(*) FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
AND QUANTIDADE = 99

-- SOLUÇÃO QUE ACHEI NO FORUM: HOUVE UMA CONSULTA ANTERIOR NA AULA DIZENDO QUE A MAIOR
--QUANTIDADE VENDIDA PARA O [CODIGO DO PRODUTO] = '1101035' ERA IGUAL A 99
--ENTÃO O PROFESSOR PEGOU QUANTAS VEZES O 99 APARECEU, QUE FOI 79 VEZES.

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) as [SOMA LIMITE] FROM [TABELA DE CLIENTES]
WHERE [ESTADO] = 'SP' GROUP BY BAIRRO, ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 140000

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO 
	HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT 
	EMBALAGEM, 
	SUM([PREÇO DE LISTA]) AS SOMA, 
	MAX([PREÇO DE LISTA]) AS VALOR_MAXIMO, 
	MIN([PREÇO DE LISTA]) AS VALOR_MININO
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT 
	EMBALAGEM,
	SUM([PREÇO DE LISTA]) AS SOMA,
	MAX([PREÇO DE LISTA]) AS MAXIMO,
	MIN([PREÇO DE LISTA]) AS MINIMO
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM
	HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT 
	EMBALAGEM,
	SUM([PREÇO DE LISTA]) AS SOMA,
	MAX([PREÇO DE LISTA]) AS MAXIMO,
	MIN([PREÇO DE LISTA]) AS MINIMO
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM
	HAVING SUM([PREÇO DE LISTA]) <= 80
	AND MAX([PREÇO DE LISTA]) >= 6

-- EXERCICIO Quais são os clientes que fizeram mais de 2000 compras em 2016?

SELECT TOP 1 * FROM [NOTAS FISCAIS]

SELECT 
	CPF, 
	COUNT(NUMERO) AS NUMERO_DE_COMPRAS
FROM [NOTAS FISCAIS] GROUP BY CPF
	HAVING MAX(NUMERO) >= 2000

-- RESPOSTA PROFESSOR
SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS] 
WHERE YEAR(DATA) = 2016 
GROUP BY CPF 
HAVING COUNT(*) > 2000

SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '50534475787'

SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS] 
--WHERE YEAR(DATA) = 2016 
GROUP BY CPF 
HAVING COUNT(*) > 2000


