SELECT * FROM [TABELA DE VENDEDORES]
SELECT * FROM [NOTAS FISCAIS]

-- JUNTANDO ESSAS DUAS TABELAS SEM ALIAS(APELIDO)

SELECT * FROM [TABELA DE VENDEDORES]
INNER JOIN [NOTAS FISCAIS] 
ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA

-- JUNTANDO ESSAS DUAS TABELAS COM ALIAS(APELIDO) TRAZENDO O MESMO RESULTADO

SELECT * FROM [TABELA DE VENDEDORES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.MATRICULA = B.MATRICULA

-- A CONSULTA VAI ATRAZER APENAS MATRICULA E NOME  DE VENDEDORES E VAI CONTAR A 
--QUANTIDADE DE VENDAS DE CADA UM

SELECT 
	[TABELA DE VENDEDORES].MATRICULA,
	[TABELA DE VENDEDORES].NOME,
	COUNT(*)
FROM [TABELA DE VENDEDORES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA
	GROUP BY [TABELA DE VENDEDORES].MATRICULA,
			 [TABELA DE VENDEDORES].NOME

-- MESMA CONSULTA, MAS TAMBÉM AGRUPANDO POR ANO 
SELECT 
	[TABELA DE VENDEDORES].MATRICULA,
	[TABELA DE VENDEDORES].NOME,
	YEAR(DATA),
	COUNT(*)
FROM [TABELA DE VENDEDORES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA
	GROUP BY [TABELA DE VENDEDORES].MATRICULA,
			 [TABELA DE VENDEDORES].NOME,
			 YEAR(DATA)

-- MESMA CONSULTA AGRUPANDO POR ANO E ORDENANDO AS DATAS

SELECT 
	[TABELA DE VENDEDORES].MATRICULA,
	[TABELA DE VENDEDORES].NOME,
	YEAR(DATA),
	COUNT(*)
FROM [TABELA DE VENDEDORES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA
	GROUP BY [TABELA DE VENDEDORES].MATRICULA,
			 [TABELA DE VENDEDORES].NOME,
			 YEAR(DATA)
	ORDER BY YEAR(DATA), [TABELA DE VENDEDORES].NOME

-- ORDENANDO POR NOME DO VENDEDOR, DEPOIS POR DATA
SELECT 
	[TABELA DE VENDEDORES].MATRICULA,
	[TABELA DE VENDEDORES].NOME,
	YEAR(DATA),
	COUNT(*)
FROM [TABELA DE VENDEDORES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE VENDEDORES].MATRICULA = [NOTAS FISCAIS].MATRICULA
	GROUP BY [TABELA DE VENDEDORES].MATRICULA,
			 [TABELA DE VENDEDORES].NOME,
			 YEAR(DATA)
	ORDER BY [TABELA DE VENDEDORES].NOME, YEAR(DATA)


-- EXERCICIO: Obtenha o faturamento anual da empresa. Leve em consideração que o 
--valor financeiro das vendas consiste em multiplicar a quantidade pelo preço.

SELECT * FROM [ITENS NOTAS FISCAIS]
SELECT * FROM [NOTAS FISCAIS]

SELECT QUANTIDADE, PREÇO, SUM(QUANTIDADE * PREÇO) AS FATURAMENTO, YEAR(DATA)
FROM [ITENS NOTAS FISCAIS] INF
INNER JOIN [NOTAS FISCAIS] NF
ON INF.NUMERO = NF.NUMERO
GROUP BY (QUANTIDADE * PREÇO), QUANTIDADE, PREÇO, YEAR(DATA)
ORDER BY YEAR(DATA)

-- SOLUCAO DO PROFESSOR
SELECT YEAR(DATA), SUM (QUANTIDADE * [PREÇO]) AS FATURAMENTO
FROM [NOTAS FISCAIS] NF INNER JOIN [ITENS NOTAS FISCAIS] INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA)


