-- CONSTRUÇÃO DE RELATÓRIO QUE EXIBE QUAL SABOR DE PRODUTO MAIS DEU FATURAMENTO NA EMPRESA
-- SUCOS_VENDAS NO ANO DE 2016 E A PORCENTAGEM DE PARTICIPAÇÃO DAS VENDAS NO FATURAMENTO ANUAL

-- TABELAS QUE SERÃO RELACIONADAS:

SELECT TP.SABOR FROM [TABELA DE PRODUTOS] TP

SELECT NF.DATA FROM [NOTAS FISCAIS] NF

SELECT (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS] INF

-- JUNTANDO ESSAS TABELAS

SELECT TP.SABOR, NF.DATA, (INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO

-- TRAZENDO FATURAMENTO ANUAL POR SABOR DE PRODUTO

SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY TP.SABOR, YEAR(NF.DATA)

-- TRAZENDO APENAS O ANO DE 2016 PARA CADA SABOR DE SUCO

SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA)

-- TRAZENDO O TOTAL DE VENDAS DE TODOS OS PRODUTOS EM 2016

SELECT  YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY  YEAR(NF.DATA)

-- AS DUAS CONSULTAS ANTERIORES SERÃO JUNTAS

SELECT AUX1.SABOR, AUX1.ANO, CONVERT(DECIMAL(15,2), AUX1.FATURAMENTO) AS FATURAMENTO,
CONVERT(VARCHAR,CONVERT(DECIMAL(15,2),(AUX1.FATURAMENTO / AUX2.TOTAL) * 100))  + ' % ' AS PERCENTUAL FROM
(SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA)) AS AUX1
INNER JOIN (
SELECT  YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY  YEAR(NF.DATA)) AS AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC