SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]

SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- USANDO UNION (NÃO MOSTRA LINHAS REPETIDAS)
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]
UNION
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- USANDO UNION ALL(MOSTRA LINHAS REPETIDAS)
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO FROM [TABELA DE CLIENTES]
UNION ALL
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO FROM [TABELA DE VENDEDORES]

-- ERRO DE TIPOS NÃO CORRESPONDENTES (DATA É DO TIPO DATE E NOME É DO TIPO VARCHAR)
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
UNION ALL
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME FROM [TABELA DE VENDEDORES]

-- SOLUÇÃO PARA O ERRO ANTERIOR
SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME FROM [TABELA DE CLIENTES]
UNION ALL
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME FROM [TABELA DE VENDEDORES]

SELECT DISTINCT [TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME, 'CLIENTE' FROM [TABELA DE CLIENTES]
UNION ALL
SELECT DISTINCT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME, 'VENDEDOR' FROM [TABELA DE VENDEDORES]

