-- EXEMPLO DA AULA DE SUB CONSULTA, BUSCA APENAS RESULTADOS QUE APARECEM DENTRO DA SUB CONSULTA
SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PREÇO
FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PREÇO FROM [TABELA DE PRODUTOS]GROUP BY EMBALAGEM)
AS NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PREÇO <= 5

-- AQUI A SUB CONSULTA VAI SE TRANSFORMAR EM UMA VIEW USANDO O ASSISTENTE DE CRIAÇÃO DE VIEW
-- EXIBIÇÕES > BOTÃO DIREITO > NOVA EXIBIÇÃO > COLAR O CÓDIGO ABAIXO
SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PREÇO FROM [TABELA DE PRODUTOS]GROUP BY EMBALAGEM

-- USANDO A VIEW CRIADA
SELECT * FROM VW_EMBALAGENS

-- SUBSTITUINDO A SUB CONSULTA PELA VIEW CRIADA
SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PREÇO
FROM VW_EMBALAGENS
AS NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PREÇO <= 5